radar:
  id: 'radar'
  name: 'Method radar'
  showAllSectorsText: 'All quadrants'
  legendDropdownText: 'Legend'
  defaultColor: '#7db6b0'
  renderResolution: 518
  linkPrefix: '/glossary/'
  linkSuffix: ''

sector:
  showName: true
  nameOffset: 5

segment: 
  colorGradient: true
  colorGradientLimit: 1.5
  showName: false
  padding: 4

blip:
  size: 1
  defaultColor: '#1e7d73'
  margin: 10
  outerCircleRadius: 0