radar:
  id: 'radar'
  name: 'Method radar'
  showAllSectorsText: 'All quadrants'
  legendDropdownText: 'Legend'
  defaultColor: '#7db6b0'
  renderResolution: 518

sector:
  showName: true
  nameOffset: 5

segment: 
  colorGradient: true
  colorGradientLimit: 1.5
  showName: true
  padding: 4

blip:
  size: 12
  defaultColor: '#1e7d73'
  margin: 4